#!/usr/bin/env bash
GOWORKONEVVARS=$(goworkon switch $@)
if [ $? -eq 0 ]; then
  while read -r oneenvvar; do
     eval "export $oneenvvar"
  done <<< "$GOWORKONEVVARS"
else
  echo "cant switch to $@"
fi

